# Generated by Django 5.0.6 on 2024-06-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0002_alter_post_options_post_artist_post_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(max_length=500),
        ),
    ]
