# Generated by Django 5.0.6 on 2024-06-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
