# Generated by Django 5.0.6 on 2024-06-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0005_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url",
        ),
    ]
