# Generated by Django 5.0.6 on 2024-06-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0008_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
